-- TravelDiary Supabase schema
-- Supabase SQL Editor에 이 파일 전체를 붙여넣고 Run 하면 됩니다.

create table if not exists public.trips (
  trip_id text primary key,
  meta_json jsonb not null default '{}'::jsonb,
  diary_json jsonb,
  photo_feedback_json jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  trip_id text not null references public.trips(trip_id) on delete cascade,
  lat double precision not null,
  lng double precision not null,
  time timestamptz not null,
  accuracy_m double precision,
  created_at timestamptz not null default now()
);

create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  trip_id text not null references public.trips(trip_id) on delete cascade,
  photo_json jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_trips_created_at
  on public.trips(created_at desc);

create index if not exists idx_locations_trip_time
  on public.locations(trip_id, time asc, id asc);

create index if not exists idx_photos_trip_id
  on public.photos(trip_id, id asc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_trips_updated_at on public.trips;
create trigger set_trips_updated_at
before update on public.trips
for each row
execute function public.set_updated_at();

alter table public.trips enable row level security;
alter table public.locations enable row level security;
alter table public.photos enable row level security;

-- 현재 앱은 서버에서 service role key로 접근합니다.
-- service role은 RLS를 우회하므로 별도 공개 정책을 만들지 않습니다.
-- anon/public key로 브라우저에서 직접 DB를 읽고 쓰게 만들지 마세요.
